### ISSUE TITLE
Styling issues on 27" iMac

### ISSUE THREAD

**Issue by benbrehaut** [benbrehaut/benb.uk#16]
- Back to top arrow on footer is not contained. Add position: relative onto ``site-footer__content``

- Fix issue with homepage intro being stuck onto the left side of the screen.

````scss
.home-content {
  max-width: 1440px;
  margin-left: auto;
  margin-right: auto;
  display: flex;
  flex-flow: row wrap;
  align-items: center;
  padding-left: 1rem;
  padding-right: 1rem;
}
````

````html
<section class="home _text-color-light">
    <section class="home-container">
<div class="home__inner _anim-fade-in-left">
        <h2 class="home-title--lrg _text-color-light">Hi, I'm Ben.</h2>
        <h3 class="home-title--lrg _text-color-light">I am a <span class="_text-color-secondary">Front-End Developer</span> based in the sunny town of <span class="_text-color-secondary">Bournemouth</span></h3>
        <a href="https://s3-eu-west-1.amazonaws.com/benb.awsbucket/ben-brehaut-cv-online.pdf" onclick="ga('send', 'event', { eventCategory: 'click', eventAction: 'cv', eventLabel: 'home'});" class="btn btn-primary btn-lrg btn--active">View my CV</a>
    </div>
</section>
</section>
````
